USE [master]
GO

/****** Object:  Database [SteveSuggestion]    Script Date: 5/22/2018 6:45:08 PM ******/
CREATE DATABASE [SteveSuggestion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SteveSuggestion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SteveSuggestion.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SteveSuggestion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\SteveSuggestion_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SteveSuggestion] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SteveSuggestion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SteveSuggestion] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SteveSuggestion] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SteveSuggestion] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SteveSuggestion] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SteveSuggestion] SET ARITHABORT OFF 
GO

ALTER DATABASE [SteveSuggestion] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SteveSuggestion] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SteveSuggestion] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SteveSuggestion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SteveSuggestion] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SteveSuggestion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SteveSuggestion] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SteveSuggestion] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SteveSuggestion] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SteveSuggestion] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SteveSuggestion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SteveSuggestion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SteveSuggestion] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SteveSuggestion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SteveSuggestion] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SteveSuggestion] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SteveSuggestion] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SteveSuggestion] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SteveSuggestion] SET  MULTI_USER 
GO

ALTER DATABASE [SteveSuggestion] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SteveSuggestion] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SteveSuggestion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SteveSuggestion] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SteveSuggestion] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SteveSuggestion] SET QUERY_STORE = OFF
GO

USE [SteveSuggestion]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SteveSuggestion] SET  READ_WRITE 
GO


